name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ubuntu Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /home/ubuntu/Reddit-to-Bluesky/
            git pull origin main
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
          tryKeyboard: true
          port: 22
        env:
          CI: true